include("${CMAKE_CURRENT_LIST_DIR}/cmake/NuGetTools.cmake")

nuget_merge_nuspec_files(OUTPUT "${MERGE_OUTPUT}" INPUTS ${MERGE_INPUTS})
nuget_pack(NUSPEC_FILEPATH "${MERGE_OUTPUT}" OUTPUT_DIRECTORY "${NUPKG_OUTPUT_DIRECTORY}")
